config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users
  devise_scope :user do
    get "/" => "devise/sessions#new"
  end

  # patient namespace
  namespace :patient do
    resources :patients
  end

  #doctor namespace
  namespace :doctor do
    resources :doctors
    # match "doctors/appointment_status"
    match "/appointment_status",to:"doctors#appointment_status", as: :appointment, via: [:get, :post]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < User
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < User
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:doctor, :patient]
  after_initialize :set_default_role, :if => :new_record?
  
  private
  
  def set_default_role
    self.role ||= :patient
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!, except: ["/"]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_in_path_for(resource)
    case resource.role.to_sym
      when :patient then patient_patients_path
      when :doctor then doctor_doctors_path
    end
  end


  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || after_sign_in_path_for(current_user))
  end
end

app/controllers/doctor/doctors_controller.rb
class Doctor::DoctorsController < ApplicationController
  before_action :verify_authorized

  def index
    @appointment = Appointment.where(doctor_id: current_user.id)
  end

  def appointment_status
    appointment = params[:appointment]
    @appointment = Appointment.find(appointment)
    status = params[:status]
    @appointment.status = status
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to doctor_doctors_path, notice: 'Appointment status changed.' }
      else
        format.html { redirect_to doctor_doctors_path }
      end
    end
  end

  private

    def verify_authorized
      authorize :common, :is_doctor?
    end
end

app/controllers/patient/patients_controller.rb
class Patient::PatientsController < ApplicationController
  before_action :verify_authorized

  def index
    @doctors = Doctor.all.where(role: "doctor")
    @appointments = Appointment.where(patient_id: current_user.id)
  end
  
  def create
    apoint_date = DateTime.new(params["appointment_date(1i)"].to_i,params["appointment_date(2i)"].to_i,params["appointment_date(3i)"].to_i,params["appointment_date(4i)"].to_i,params["appointment_date(5i)"].to_i)
    @appointment = Appointment.new
    @appointment.patient_id = current_user.id
    @appointment.doctor_id = params[:doctor_id]
    @appointment.appointment_date = apoint_date
    respond_to do |format|
      if @appointment.save
        #Mailer code you have to write here
        AppointmentEmailMailer.appointment_mail(@appointment).deliver_now
        format.html { redirect_to patient_patients_path, notice: 'Appointment was successfully created.' }
      else
        format.html { redirect_to patient_patients_path }
      end
    end
  end

  private

    def verify_authorized
      authorize :common, :is_patient?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctor/doctors/index.html.erb
<div class="d-flex">
  <h1>Appointment List</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Patient Name</th>
      <th>Appointment Status</th>
      <th>Appointment Date</th>

      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @appointment.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.first_name %></td>
        <% if appointment.status == true %>
          <td>"Appointment Accepted"</td>
        <% elsif appointment.status == false %>
         <td>"Appointment Rejected"</td>
        <% else %>
        <td>"Pending"</td>
        <% end %>
        <td><%= appointment.appointment_date %></td>
        <% if appointment.status == false %>
           <td><%= link_to "<button>Accept</button>".html_safe, doctor_appointment_url(:appointment => appointment, :status => true), method: :post %></td>
        <% elsif appointment.status == true  %>
          <td><%= link_to "<button>Reject</button>".html_safe, doctor_appointment_url( :appointment => appointment, :status => false), method: :post %></td>
        <% elsif appointment.status == nil  %>
          <td><%= link_to "<button>Accept</button>".html_safe, doctor_appointment_url(:appointment => appointment, :status => true), method: :post, class: "btn btn-primary" %></td>
          <td><%= link_to "<button>Reject</button>".html_safe, doctor_appointment_url( :appointment => appointment, :status => false), method: :post,class: "btn btn-primary" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvpApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item active">
        <span class="nav-link">Welcome <%= current_user.first_name %>!</span>
      </li>
      <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    <% end %>
  </ul>
</div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/patient/patients/index.html.erb
<div class="d-flex">
  <h1>Book Appointment</h1>
  <div class="ml-auto">
  <%= form_with url: patient_patients_path do |form| %>
    <div class="form-group select-field">
      <%= form.label :Appointment_Date %>
      <%= form.datetime_select :appointment_date, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year , end_year: Date.today.year}, {required: true} %>
    </div>
  
    <div class="form-group">
      <%= form.label :Doctors %>
      <%= form.select(:doctor_id, @doctors.collect {|u| [u.first_name, u.id]}, :prompt => 'Select doctor') %>
    </div>
  
    <div class="form-group">
      <%= form.submit "Save", class: 'btn btn-primary' %>
    </div>
  <% end %>
  </div>
</div>


<div class="d-flex">
  <h1>Booked Appointment</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Doctor First Name</th>
      <th>Doctor Last Name</th>
      <th>Doctor Email</th>
      <th>Appointment Date time</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appoint| %>
      <tr>
        <td><%= appoint.doctor.first_name %></td>
        <td><%= appoint.doctor.last_name %></td>
        <td><%= appoint.doctor.email %></td>
        <td><%= appoint.appointment_date %></td>
        <% if appoint.status == true %>
          <td>"Appointment Accepted"</td>
        <% elsif appoint.status == false %>
         <td>"Appointment Rejected"</td>
        <% else %>
        <td>"Pending"</td>
        <% end %>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>